version: "3"

networks:
  recruitment-test:
    driver: bridge

services:
  database:
    image: postgres
    container_name: recruitment-test-db
    ports:
      - ${DATABASE_PORT:-5432}:5432
    networks:
      - recruitment-test
    environment:
      - POSTGRES_DB=recruitment_test_dev
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: recruitment-test-backend
    ports:
      - "4000:4000"
    networks:
      - recruitment-test
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - database
    stdin_open: true
    tty: true

volumes:
  pgdata: null
